# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  # config.vm.box_version = "2004.01"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
  
  boxes = [
  { :name => "client",
    :ip => "192.168.56.10",
  },
  { :name => "backup",
    :ip => "192.168.56.15",
  },
  ]
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]
      
  end
 end	
end

